platform :ios, '14.0'
use_frameworks!

# 避免 Xcode 缓存 Pods
install! 'cocoapods', :disable_input_output_paths => true

target 'App' do
  pod 'Capacitor'
  pod 'CapacitorCordova'
  # 如果你有其他插件，这里继续添加
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
